### ISSUE TITLE
Feedback on Assignment

### ISSUE THREAD

**Issue by Gchism94** [INFO-523-Exercises/intro-R-Python-Aravind-shrenivas#1]
Hi Aravind, 

Really great work on the assignment. 

My only minor issue is that you need to add Authorship (first name, last name) to the quarto document. 

I am giving you full credit, contingent on you resolving the minor issue by September 15th.
-Greg

**Comment by Aravind-shrenivas** [comment]
Hi Greg,

Thank you for your kind words. I have added author to my quarto document and pushed it.
